import { Inter } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/components/global/HeaderTop";
import Menu from "@/components/global/Menu";
import Footer from "@/components/global/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop />
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
